version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
      
    working_directory: /go/src/github.com/ecadlabs/go-tezos
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
